apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-service
          image: teleiostejiriacr.azurecr.io/notification-service:v1.1
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: notification-secret
          env:
          - name: FIREBASE_CREDENTIALS_PATH
            value: /app/firebase/firebase-credentials.json

          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/firebase
              readOnly: true

          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
         # livenessProbe:
          #  httpGet:
          #    path: /health/
          #    port: 8000
          #  initialDelaySeconds: 10
          #  periodSeconds: 15

      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials

