apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: rideshare
  labels:
    app: notification-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: acr-auth

      containers:
        - name: notification-service
          image: teleiosdupeacr01.azurecr.io/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: JWT_SECRET_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: REDIS_URL
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: SENDGRID_API_KEY
            - name: SENDGRID_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: SENDGRID_FROM_EMAIL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_CREDENTIALS_PATH
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: FIREBASE_CREDENTIALS_PATH
          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/firebase/firebase-credentials.json
              subPath: firebase-credentials.json
              readOnly: true

          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"

      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
            items:
              - key: firebase-credentials.json
                path: firebase-credentials.json
