apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: rideshare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: teleiosdupeacr01.azurecr.io/notification-service:latest
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: notification-service-secrets

          env:
            - name: FIREBASE_CREDENTIALS_PATH
              value: /app/firebase/firebase-credentials.json

          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/firebase
              readOnly: true

          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"

          # readinessProbe:
          #   httpGet:
          #     path: /health/
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10

      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
