apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: rideshare
type: Opaque
stringData:
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  REDIS_URL: "${{ secrets.REDIS_URL }}"
  JWT_SECRET_KEY: "${{ secrets.JWT_SECRET_KEY }}"
  SENDGRID_API_KEY: "${{ secrets.SENDGRID_API_KEY }}"
  SENDGRID_FROM_EMAIL: "${{ secrets.SENDGRID_FROM_EMAIL }}"
  FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: rideshare
type: Opaque
stringData:
  firebase-credentials.json: "${{ secrets.FIREBASE_CREDENTIALS_JSON }}"
